### ISSUE TITLE
Images in EXE file not working

### ISSUE THREAD

**Issue by Rishikesh-kumar-7258** [Rishikesh-kumar-7258/flappyBird#3]
When I make an  .exe file using PyInstaller in python. The images are not loading. When I run the game in my computer it works fine, while when I told my friend to try this game this game showed that the problem in loading the images.

**Comment by museHD** [comment]
When I try to run the latest main.exe, I get the following error:

`pygame 2.0.1 (SDL 2.0.14, Python 3.9.6)`
`Hello from the pygame community. https://www.pygame.org/contribute.html`
`Traceback (most recent call last):`
`  File "main.py", line 14, in <module>`
`  File "States\playstate.py", line 24, in __init__`
`  File "classes\birdClass.py", line 21, in __init__`
`FileNotFoundError: No such file or directory.`
`[15816] Failed to execute script 'main' due to unhandled exception!`

It seems like it can't load the images because it expects the Images folder containing all the required images. I confirmed this by placing the .exe file in the main project directory which ran smoothly, as shown below. 

![image](https://user-images.githubusercontent.com/57558058/136179520-8efb521e-ca39-4ee3-bfde-d9b92454b4f7.png)

I would suggest removing the `--onefile` flag when building it, as this allows pyinstaller to create other folders containing assets. 
If a single exe file is necessary, you might want to try including EACH folder while building, as shown in the [docs](https://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#the-toc-and-tree-classes)

Cheers!
